### ISSUE TITLE
Dataset is not avai

### ISSUE THREAD

**Issue by renatoviolin** [GoogleCloudPlatform/ai-platform-text-classifier-shap#1]
The download link 
!gsutil cp 'gs://cloudml-demo-lcm/SO_ml_tags_avocado_188k_v2.csv' ./

is returning "ServiceException: 401 Anonymous caller does not have storage.objects.get access to cloudml-demo-lcm/SO_ml_tags_avocado_188k_v2.csv."

**Comment by sararob** [comment]
The access on this file requires you to be authenticated with a Google account. Can you try running either:

`gcloud auth login
`

or if you're in Colab:

```
from google.colab import auth
auth.authenticate_user()
```

and let me know if you can access it? If so I'll add this to the readme. Thanks!

**Comment by renatoviolin** [comment]
Thanks, 
using
from google.colab import auth
auth.authenticate_user()
worked now.

**Comment by sivavaraprasadg** [comment]
I tried to access the csv but I got this Dear Sara 

AccessDeniedException: 403 gsivavaraprasad@gmail.com does not have storage.objects.list access to the Google Cloud Storage bucket.

please help

**Comment by sivavaraprasadg** [comment]
I tried this 

from google.colab import auth
auth.authenticate_user()

I got access but still the above problem is there
